version: '3.8'

services:
  reservations:
    build:
      context: . # where to run docker build from, we want root, this file is in root, hence .
      dockerfile: ./apps/reservations/Dockerfile
      target: development # development stage in Dockerfile
    command: yarn run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app # mount entire project (local machine) to app dir in container

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
